GIZLB_SQL_DB="gizsurvey"
GIZLB_SQL_USER="gizlinebot"
GIZLB_SQL_PASS="Mpmc3EzwUU06Pq9hq8T55fEnaN2okglRd5CPS2i4fcA"
GIZLB_SQL_HOST="127.0.0.1"
GIZLB_SQL_PORT="3306"

GIZLB_LINE_SECRET=""
GIZLB_LINE_TOKEN=""

# host where the frontend files, API and linewebhook will be served from
# used as {{.Hostname}} variable in templated vars
GIZLB_HOSTNAME="https://7c44107f.ngrok.io"
PORT="8888"

# Papertrail integration
GIZLB_PTRAIL_PORT=""
GIZLB_PTRAIL_HOST=""
GIZLB_PTRAIL_APP=""
