# .goreleaser.yml Build customization
builds:
  - main: main.go
    binary: linebot
    goos:
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Tux
